output_path = "HI/"
global_mean_read_length = 2000
random_seed = 1

[parameters]
sample_name = "zymo"
experiment_name = "icarust_zymo"
flowcell_name = "FAQ1234"
experiment_duration_set = 4800
device_id = "D001"
position = "P001"

[[sample]]
name = "lm"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/lm.squiggle.npy"
weight = 1000000

[[sample]]
name = "pa"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/pa.squiggle.npy"
weight = 100000

[[sample]]
name = "bs"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/bs.squiggle.npy"
weight = 10000

[[sample]]
name = "ec"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/ec.squiggle.npy"
weight = 1000

[[sample]]
name = "se"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/se.squiggle.npy"
weight = 1000

[[sample]]
name = "lf"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/lf.squiggle.npy"
weight = 100

[[sample]]
name = "ef"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/ef.squiggle.npy"
weight = 10

[[sample]]
name = "sa"
input_genome = "/nfs/research/goldman/lukasw/simION/icarust_squiggles/squiggles/sa.squiggle.npy"
weight = 1





